include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_return: error
    dead_code: error
    unused_import: error
    unused_local_variable: error

linter:
  rules:
    - prefer_single_quotes
    - always_declare_return_types
    - avoid_redundant_argument_values
    - prefer_const_constructors
